# This workflow is used to deploy updates to the website on pushes to main
# It uses the cloudflare wrangler action to make updates
# It is dependent on the CLOUDFLARE_API_TOKEN Github secret being set.

name: Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Deploy
              uses: cloudflare/wrangler-action@v3 # https://developers.cloudflare.com/workers/ci-cd/external-cicd/github-actions/#github-actions
              env:
                  PUSHOVER_API_KEY: ${{ secrets.PUSHOVER_API_KEY }}
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  wranglerVersion: "4.32.0"
                  secrets: |
                      PUSHOVER_API_KEY
